// import Footer from './components/Footer/Footer';


// const Footer = () => {
//   return (
//     <Footer className={Footer}>
//       ©2023, Generated by create next app.
//     </Footer>
//   );
// };

// export default Footer;