import type { Metadata } from 'next'
import { Cabin } from 'next/font/google'
import './globals.css'

const inter = Cabin({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Data Fetching UI Dev',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-indigo-300`}>{children}</body>
    </html>
  )
}
