import type { Metadata } from 'next'
import { Cabin } from 'next/font/google'
import Navbar from './components/Navbar'
import './globals.css'
import Footer from './components/Footer/Footer'

const inter = Cabin({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Data Fetching UI Dev',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-indigo-300 pt-[80px] min-h-screen`}>
        <Navbar />

        {children}
        <Footer/>
      </body>

      
    </html>
  )
}



